### PR TITLE
Update defaults aws_inspector_url to official URL

### LINKED ISSUE #6: Update Default URL for Inspector Agent Installer Script
Thanks for your efforts, this is an excellent little role. I discovered this during my analysis of  geerlingguy/ansible-role-aws-inspector#5, but the official upstream URL for the installer is not a Cloudfront URL, but a designated DNS name [in the official docs](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html), the official URL to download the agent is now below.

https://inspector-agent.amazonaws.com/linux/latest/install

Note, testing the current Ansible module and this new URL return the exact same output as of the date of file this ticket.

```sh
$ curl --silent -L -o install_cloudfront https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install
$ curl --silent -L -o install_newurl https://inspector-agent.amazonaws.com/linux/latest/install
$ sha256sum install_cloudfront install_newurl 
19ab6161d71ed32da53d6664bdbf7ee177ef85dd09eeee1fb731772922c2869a  install_cloudfront
19ab6161d71ed32da53d6664bdbf7ee177ef85dd09eeee1fb731772922c2869a  install_newurl
$ diff install_cloudfront install_newurl
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by tohch4**
Closes #6.

### CODE REVIEW

**Comment by nc-fosterr** [comment]
This needs to be re-opened. I got bitten by this. Fortunately, I am able to override, but ideally, upstream should have the correct URL.

**Comment by tohch4** [comment]
> This needs to be re-opened. I got bitten by this. Fortunately, I am able to override, but ideally, upstream should have the correct URL.

I think it is inevitable, given the linked blog post. I will likely sponsor @geerlingguy from a personal account, but he is clear in no uncertain terms that does not guarantee us any special treatment. 🤷

**Comment by geerlingguy** [comment]
Sometimes it just takes asking a few times ;)

**Comment by geerlingguy** [comment]
This change is in 1.2.0.

**Comment by nc-fosterr** [comment]
@geerlingguy So say your name like Beattlejuice? Got it. ;)

**Pull request merged**
